name: Weglot Technology Rules

on:
  pull_request:
  push:
    paths:
      - "technology-rules/**"
    tags:
      - "*"

jobs:
  test:
    name: Check JSON Schemas, build & publish
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "12"
          registry-url: https://npm.pkg.github.com/
          scope: "@weglot"
      - name: Cache dependencies
        id: cache-dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache
            **/node_modules
          key: ${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

      - name: Run tests
        run: yarn workspace @weglot/technology-rules test

      - name: Build
        run: yarn workspace @weglot/technology-rules build

      - name: Publish on Github registry
        if: startsWith(github.ref, 'refs/tags/')
        working-directory: ./technology-rules
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
